exclude = ["node_modules/**", "target/**", "dist/**", "docs/**", "fuzz/target/**"]

[formatting]
align_entries        = true
indent_string        = "  "
array_trailing_comma = true
array_auto_expand    = false
column_width         = 200
