import { useActionState } from "react";
import type { JSX } from "react";

import {
  SEED_ENTROPY_BYTES,
  decodePsbt,
  decodeSeed,
  encodePsbtParts,
  encodeSeed,
  parseHex,
  randomBytes,
  toHex,
} from "./playground.ts";
import { Qr } from "./Qr.tsx";

function messageOf(e: unknown): string {
  return e instanceof Error ? e.message : "failed";
}

function field(data: FormData, name: string): string {
  const value = data.get(name);
  return typeof value === "string" ? value : "";
}

function attempt<S extends { error: string }>(state: S, run: (s: S) => S, onError: Partial<S>): S {
  try {
    return { ...run(state), error: "" };
  } catch (error) {
    return { ...state, ...onError, error: messageOf(error) };
  }
}

type SeedState = {
  hex: string;
  ur: string;
  decoded: string;
  error: string;
};

const INITIAL_SEED: SeedState = { hex: "", ur: "", decoded: "", error: "" };

function seedAction(prev: SeedState, data: FormData): SeedState {
  const input: SeedState = { ...prev, hex: field(data, "hex"), ur: field(data, "ur") };
  switch (data.get("intent")) {
    case "generate":
      return { ...input, hex: toHex(randomBytes(SEED_ENTROPY_BYTES)), error: "" };
    case "encode":
      return attempt(input, (s) => ({ ...s, ur: encodeSeed(parseHex(s.hex)) }), { ur: "" });
    case "decode":
      return attempt(input, (s) => ({ ...s, decoded: toHex(decodeSeed(s.ur)) }), { decoded: "" });
    default:
      return input;
  }
}

type PsbtState = {
  hex: string;
  parts: string[];
  urText: string;
  decoded: string;
  error: string;
};

const INITIAL_PSBT: PsbtState = { hex: "", parts: [], urText: "", decoded: "", error: "" };

function psbtAction(prev: PsbtState, data: FormData): PsbtState {
  const input: PsbtState = { ...prev, hex: field(data, "hex"), urText: field(data, "ur") };
  switch (data.get("intent")) {
    case "encode":
      return attempt(
        input,
        (s) => {
          const parts = encodePsbtParts(parseHex(s.hex));
          return { ...s, parts, urText: parts.join("\n") };
        },
        { parts: [], urText: "" },
      );
    case "decode":
      return attempt(input, (s) => ({ ...s, decoded: toHex(decodePsbt(s.urText)) }), {
        decoded: "",
      });
    default:
      return input;
  }
}

export function App(): JSX.Element {
  return (
    <main>
      <h1>UR playground</h1>
      <p className="lede">
        Local <code>ur:seed</code> and <code>ur:psbt</code> encode/decode. Nothing is sent.
        Generated bytes are not a wallet.
      </p>
      <SeedPanel />
      <PsbtPanel />
    </main>
  );
}

function SeedPanel() {
  const [state, action] = useActionState(seedAction, INITIAL_SEED);

  return (
    <section>
      <h2>Seed</h2>
      <form action={action}>
        <label htmlFor="seed-hex">Entropy hex</label>
        <textarea id="seed-hex" name="hex" rows={2} spellCheck={false} defaultValue={state.hex} />
        <div className="row">
          <button type="submit" name="intent" value="generate">
            Generate 16 bytes
          </button>
          <button type="submit" name="intent" value="encode">
            Encode ur:seed
          </button>
        </div>
        {state.ur === "" ? null : (
          <div className="result">
            <Qr value={state.ur} label="ur:seed" />
            <pre>{state.ur}</pre>
          </div>
        )}
        <label htmlFor="seed-ur">Paste UR</label>
        <textarea id="seed-ur" name="ur" rows={3} spellCheck={false} defaultValue={state.ur} />
        <button type="submit" name="intent" value="decode">
          Decode
        </button>
      </form>
      {state.decoded === "" ? null : <pre>{state.decoded}</pre>}
      {state.error === "" ? null : <p className="error">{state.error}</p>}
    </section>
  );
}

function PsbtPanel() {
  const [state, action] = useActionState(psbtAction, INITIAL_PSBT);

  return (
    <section>
      <h2>PSBT</h2>
      <form action={action}>
        <label htmlFor="psbt-hex">PSBT hex</label>
        <textarea id="psbt-hex" name="hex" rows={6} spellCheck={false} defaultValue={state.hex} />
        <button type="submit" name="intent" value="encode">
          Encode ur:psbt (maxFragmentLength 50)
        </button>
        {state.parts.length > 0 ? (
          <ol className="parts">
            {state.parts.map((part, i) => (
              <li key={part}>
                <Qr value={part} label={`${i + 1}/${state.parts.length}`} />
                <pre>{part}</pre>
              </li>
            ))}
          </ol>
        ) : null}
        <label htmlFor="psbt-ur">Paste UR parts</label>
        <textarea id="psbt-ur" name="ur" rows={6} spellCheck={false} defaultValue={state.urText} />
        <button type="submit" name="intent" value="decode">
          Decode
        </button>
      </form>
      {state.decoded === "" ? null : <pre>{state.decoded}</pre>}
      {state.error === "" ? null : <p className="error">{state.error}</p>}
    </section>
  );
}
