//! Official UR vectors exercised through the public `ur` API. Cases that need
//! the crate-internal message generator live in `src/official_vectors.rs`.

use bcur::ur::{Kind, UrType, decode, decode_message, encode, parse};
use serde_json::Value;

use crate::{hex, vector};

fn run_case(case: &Value) {
    let name = case["name"].as_str().unwrap();
    let ur = case["ur"].as_str().unwrap();
    let ur_type = UrType::new(case["urType"].as_str().unwrap()).unwrap();
    let parsed = parse(ur).unwrap();
    assert_eq!(parsed.ur_type, ur_type, "{name}");
    if case["kind"].as_str() == Some("multi") {
        assert_eq!(parsed.kind, Kind::MultiPart, "{name}");
        let seq = case["seqNum"].as_u64().unwrap() as u32;
        let count = case["seqLen"].as_u64().unwrap() as u32;
        assert_eq!(parsed.indices, Some((seq, count)), "{name}");
        let (kind, payload) = decode(ur).unwrap();
        assert_eq!(kind, Kind::MultiPart, "{name}");
        assert!(!payload.is_empty(), "{name}");
    } else {
        assert_eq!(parsed.kind, Kind::SinglePart, "{name}");
        let payload = decode_message(ur).unwrap();
        if let Some(expected) = case["cborHex"].as_str() {
            assert_eq!(hex(&payload), expected, "{name}");
        }
        assert_eq!(encode(&payload, &ur_type), ur, "{name}");
    }
}

#[test]
fn official_ur_single() {
    let doc = vector("official/ur/single.json");
    for case in doc["cases"].as_array().unwrap() {
        // `payload` cases are generated by the crate-internal message generator.
        if case["payload"].is_object() {
            continue;
        }
        run_case(case);
    }
}
