name: Release

on:
  push:
    tags: ["v*.*.*"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    uses: qntx/workflows/.github/workflows/release-rust.yml@v2
    permissions:
      contents: write
    with:
      bin: bcur
      package: bcur-cli
